"""Initial migration

Revision ID: 2a64a760f426
Revises: 
Create Date: 2024-10-22 21:07:25.678920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a64a760f426'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leaderboard_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(length=80), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('hodl', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leaderboard_entry')
    # ### end Alembic commands ###
